# Generated by Django 5.2 on 2025-06-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=1000)),
                ('Descrição', models.TextField()),
                ('Numero_alunos', models.IntegerField()),
                ('Data_inicio_curso', models.DateField(default='2025-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_inscrito', models.CharField(max_length=1000)),
                ('Telefone', models.CharField(max_length=15)),
                ('Idade', models.IntegerField(blank=True, null=True)),
                ('Bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('Educacao', models.CharField(blank=True, choices=[('Fundamental Incompleto', 'Fundamental Incompleto'), ('Fundamental Completo', 'Fundamental Completo'), ('Médio Incompleto', 'Médio Incompleto'), ('Médio Completo', 'Médio Completo'), ('Superior Incompleto', 'Superior Incompleto'), ('Superior Completo', 'Superior Completo')], max_length=23, null=True)),
                ('Periodo_estudo', models.CharField(blank=True, choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Integral', 'Integral'), ('Não Estudo', 'Não Estudo')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=20)),
                ('criado_a', models.DateTimeField(auto_now_add=True)),
                ('nome_curso', models.CharField(max_length=300)),
                ('aceito_em_lote', models.CharField(default='Não', max_length=10)),
                ('em_entrevista', models.CharField(default='Não', max_length=10)),
                ('matriculado', models.CharField(default='Não', max_length=10)),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('quantidade_faltas', models.IntegerField(default=0)),
                ('data_envio', models.DateField(default='2025-01-01')),
                ('data_envio_avaliacao', models.DateField(default='2025-01-01')),
                ('av1', models.IntegerField(default=0)),
                ('av2', models.IntegerField(default=0)),
                ('av3', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_participante', models.CharField(max_length=100)),
                ('curso_do_lote', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('max_participantes', models.IntegerField()),
                ('curso_para_processo', models.CharField(max_length=1000)),
                ('Data_inicio_aulas', models.DateField(default='2025-01-01')),
            ],
        ),
    ]
