# Generated by Django 5.2 on 2025-04-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=1000)),
                ('Descrição', models.TextField()),
                ('Numero_alunos', models.IntegerField()),
                ('Numero_Professores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('max_participantes', models.IntegerField()),
                ('curso_para_processo', models.CharField(max_length=1000)),
            ],
        ),
    ]
