# Generated by Django 5.2 on 2025-05-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255)),
                ('Telefone', models.CharField(max_length=15)),
                ('Idade', models.IntegerField(blank=True, null=True)),
                ('Bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('Educacao', models.CharField(blank=True, choices=[('Fundamental Incompleto', 'Fundamental Incompleto'), ('Fundamental Completo', 'Fundamental Completo'), ('Médio Incompleto', 'Médio Incompleto'), ('Médio Completo', 'Médio Completo'), ('Superior Incompleto', 'Superior Incompleto'), ('Superior Completo', 'Superior Completo')], max_length=23, null=True)),
                ('Periodo_estudo', models.CharField(blank=True, choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Integral', 'Integral')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=20)),
                ('criado_a', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('E_mail', models.EmailField(max_length=254, unique=True)),
                ('Senha', models.CharField(max_length=128)),
            ],
        ),
    ]
