# Generated by Django 5.2 on 2025-06-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Tipos_conta', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Professor', 'Professor')], max_length=30, null=True)),
                ('Curso', models.CharField(blank=True, max_length=100, null=True)),
                ('E_mail', models.EmailField(max_length=254, unique=True)),
                ('Senha', models.CharField(max_length=128)),
            ],
        ),
    ]
