# Generated by Django 5.2 on 2025-06-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aluno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
